/*
-- Query: SELECT * FROM laravel.products
LIMIT 0, 1000

-- Date: 2024-06-13 17:51
*/
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (1,'f9a06ce6-b3b7-40f4-b350-f3f54fa800f1','Clear Shampoo Men Anticaspa Ice Cool Menthol 400Ml','O Shampoo Anticaspa Clear Men Ice Cool Menthol foi desenvolvido para homens, pois o couro cabeludo do homem está mais propenso a caspa\r\nCom tecnologia Bio Booster que ajuda a ativar a proteção natural do couro cabeludo, acabando com a caspa recorrente*\r\nCom mentol refrescante, este shampoo deixa o couro cabeludo com sensação de refrescância que dura o dia todo\r\nEste shampoo para uso diário é indicado para homens com couro cabeludo oleoso e irritado. Para uso diário\r\nO Shampoo Anticaspa Ice Cool Menthol protege o couro cabeludo, nutrindo-o, além de proporcionar uma sensação intensa de refrescância e remoção da oleosidade\r\nO Shampoo Clear Men fortalece o couro cabeludo e acaba de vez com a caspa, deixando seu cabelo saudável e com sensação refrescante','shampoo',22.90,10,'Clear','2024-06-13 20:39:21','2024-06-13 20:39:21',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (2,'d6468b16-59f4-42c5-912b-6061177fbd41','Shampoo Antiqueda','Contém ingredientes importantes na estimulação dos folículos capilares e à maximização da saúde capilar. Os principais ingredientes são o Saw Palmetto e o Café Verde. Medicamento sob prescrição médica.','shampoo',33.33,1,'Manual','2024-06-13 20:40:01','2024-06-13 20:40:01',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (3,'cb92e642-90f0-497f-a84f-18a755aa0767','KIT SHAMPOO E CONDICIONADOR ANTIQUEDA AQ-01','Kit com shampoo e condicionador antiqueda com alta eficácia na redução da quebra, estimulo do crescimento e aumento da resistência e volume dos cabelos.','shampoo',79.00,1,'Principia','2024-06-13 20:40:59','2024-06-13 20:40:59',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (4,'db4085f2-c1e2-4b6d-a3ee-59cf1f3990df','KIT WELLA INVIGO NUTRI-ENRICH SH 1L + COND 1L','Kit tratamento para cabelos secos, ressecados ou com química em tamanho salão\r\nNutre e hidrata de maneira intensa para restaurar a saúde dos fios\r\nDesembaraça e suaviza a superfície do fio para que fique com toque macio','shampoo',237.00,1,'WELLA','2024-06-13 20:41:38','2024-06-13 20:41:38',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (5,'786b5829-0ca4-47c5-a365-cb82da4b8ea9','L\'Oréal Professionnel Serie Expert Absolut Repair Gold Quinoa + Protein - Shampoo 1,5L','** teste','shampoo',245.00,1,'L\'Oréal','2024-06-13 20:42:46','2024-06-13 20:42:46',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (6,'5c7abf08-8880-4f63-b0c6-7b52b11ddcff','TRESemmé Shampoo Tresemmé Hidratação Profunda Frasco 650Ml','HIDRATAÇÃO PROFUNDA','shampoo',22.49,1,'TRESemmé','2024-06-13 20:43:27','2024-06-13 20:43:27',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (7,'0ce94741-842f-48ad-af52-adcf767e51ac','Kit Shampoo + Condicionador Ultra Hydration TRUSS 2 x 300 ml','Vegano e Cruelty Free\r\nPara cabelos ressecados e danificados\r\nPromove uma limpeza suave, restaura e hidrata os fios que passaram por processos químicos ou agressões externas','shampoo',177.90,1,'TRUSS','2024-06-13 20:44:24','2024-06-13 20:44:24',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (8,'a9303fa6-dc0c-4e2f-aaf0-13f793daebfa','L\'Oréal Paris Elseve Shampoo Preenchedor Hidra Hialurônico, Preenche o Cabelo com Hidratação Profunda, 400 ml','O Shampoo Preenchedor Elseve Hidra Hialurônico é enriquecido com ácido hialurônico, conhecido por sua capacidade de reter até 1000x seu peso em água\r\nAo aplicar o produto, você sentirá uma transformação instantânea nos fios, proporcionando cabelos leves, soltos e saudáveis desde a primeira utilização\r\nPara utilizar, basta aplicar nos cabelos molhados, massagear suavemente e enxaguar. Repita a operação se necessário para melhores resultados.\r\nA fórmula do produto é especialmente desenvolvida para todos os tipos de cabelos, garantindo que cada fibra capilar seja preenchida e retenha a hidratação necessária.\r\nContém: 1 x L\'Oréal Paris Shampoo Preenchedor Elseve Hidra Hialurônico, Preenche o Cabelo com Hidratação Profunda, 400 ml','shampoo',15.75,10,'L\'Oréal','2024-06-13 20:45:10','2024-06-13 20:45:10',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (9,'28ffdea5-a2dd-4a47-992b-ad0e446d4c57','Shampoo Siàge Acelera O Crescimento 250ml','Descubra mais sobre\r\n\r\nShampoo Siàge Acelera O Crescimento 250ml\r\nO Shampoo Siàge Acelera O Crescimento foi feito para cabelos com dificuldade de crescimento, reduzindo e prevenindo a queda natural.\r\n\r\nSua espuma cremosa limpa sem ressecar, favorecendo o crescimento a partir de 12 lavagens. São 3 centímetros de comprimento dos fios em 2 meses e 1.500 fios em 1 mês.\r\n\r\nCom Prebiótico e Biotina em sua fórmula, esses ativos atuam diretamente no equilíbrio do couro cabeludo ativando o metabolismo do fio e estimulando o crescimento.\r\n\r\nO shampoo age em quatro dimensões para ativar o crescimento saudável:\r\n\r\n-Crescimento de até 3 cm em 2 meses;\r\n\r\n-Prolonga a vida dos fios;\r\n\r\n-Reduz e previne a queda natural;\r\n\r\n-3x menos quebra','shampoo',44.99,5,'Siàge','2024-06-13 20:45:54','2024-06-13 20:45:54',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (10,'aa7272e5-e876-41fd-83cf-0b67d854a7e0','Dove Shampoo Alivio Refrescante 400Ml','Shampoo Dove Alivio Refrescante 400Ml\r\nMarca do produto: SKALA\r\nCor do produto: Transparente\r\nTamanho do produto: 400 ml (Pacote de 1)','shampoo',22.14,7,'Dove','2024-06-13 20:46:37','2024-06-13 20:46:37',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (11,'3a58e683-a349-44b6-a3fa-46da558368df','Sabonete em Barra Protex Carvão Detox 6 unid Promo Leve Mais Pague Menos','Fórmula que combina óleo de linhaça + carvão ativado.\r\nFortalece as defesas naturais da pele.\r\nCria um efeito detox de dentro para fora.\r\nElimina 99.9% das bactérias Naturalment','soap',16.69,2,'Protex','2024-06-13 20:47:59','2024-06-13 20:47:59',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (12,'46a18b51-b103-4e26-80e0-4ba7c3f36d6d','Dove Sabonete Em Barra Branco 90G - 8Un','O Sabonete em Barra Dove Original hidrata sua pele pois possui 1/4 de creme hidratante em sua composição e agentes de limpeza suaves\r\nEste sabonete em barra não resseca a pele como sabonetes comuns e ajuda a repor nutrientes naturais que podem ser perdidos durante o banho\r\nSabão em barra com tecnologia de limpeza e manutenção da hidratação com suavidade para sua pele\r\nEste sabonete hidratante deixa a pele macia, bem cuidada e com aspecto saudável\r\nEste sabonete hidratante deixa a pele macia, bem cuidada e com aspecto saudável','soap',32.99,2,'Dove','2024-06-13 20:49:11','2024-06-13 20:49:11',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (13,'3a4e6ca9-ae24-48ee-8054-86396cfd4369','Gel de Limpeza Principia 2% Ácido Salicílico + 5% Glicerina com 350g','Controlar a oleosidade\r\nProporcionar maciez\r\nMelhorar o viço\r\nRemover impurezas\r\nDiminuir cravos e espinhas; Promover hidratação','soap',39.71,3,'Glicerina','2024-06-13 20:49:54','2024-06-13 20:49:54',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (14,'90908f21-2085-4bbb-96b9-b58943622f9e','Gel de Limpeza Principia 2% Ácido Salicílico + 5% Glicerina com 350g','Controlar a oleosidade\r\nProporcionar maciez\r\nMelhorar o viço\r\nRemover impurezas\r\nDiminuir cravos e espinhas; Promover hidratação','soap',39.71,8,'Salicílico','2024-06-13 20:50:30','2024-06-13 20:50:30',NULL);
INSERT INTO `` (`id`,`uuid`,`name`,`description`,`type`,`price`,`stock_quantity`,`brand`,`created_at`,`updated_at`,`deleted_at`) VALUES (15,'f83bb596-0f5a-42a2-82c4-01106779a70f','Sabonetes em Barra Natura TodoDia Alecrim e Sálvia 5 Unit de 90g','O sabonete em barra Tododia Alecrim e Sálvia promove agradável sensação enquanto limpa e deixa a pele macia e sedosa. Sua fórmula suave evita o ressecamento e prepara a pele para receber a combinação nutritiva duradoura de nossos hidratantes. Benefícios: Não resseca; Hidrata suavemente; Sensação de pele macia e sedosa. Conteúdo: 5 unidades, 90g cada.','soap',27.00,9,'Natura','2024-06-13 20:51:18','2024-06-13 20:51:18',NULL);
